### ISSUE TITLE
Update Gem Version

### ISSUE THREAD

**Issue by gwincr11** [burnto/nanoc-html-pipeline#5]
It appears that about a year ago there was an update to fix the `NoMethodError: undefined method register for Nanoc::Filter:Class` error, however the gem version was not bumped so the version on bundler is not up to date with the version of master in Github. Can we get the version bumped so I can update this gem?

**Comment by gjtorikian** [comment]
Closed via https://github.com/burnto/nanoc-html-pipeline/pull/6.
